ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "1200" # 20 minutes
ENV["FASTLANE_HTTP_TIMEOUT"] = "600" # 10 minutes


default_platform(:android) 

platform :android do
  desc "lane for Android Firebase App Distribution"
  lane :firebase_distribution_petfinder do
    sh "flutter clean"
    sh "flutter build apk --release"
    firebase_app_distribution(
        app: "1:1006675739293:android:70b29c32570b8c8d5c4a74",  
        firebase_cli_token: "1//036H98IuG6j_qCgYIARAAGAMSNwF-L9IrVBUbpPeFi921x3AEAciz5YcPZGczGzc3hWhFLVPRcsbjIYUFQb-0RUDKZTYzyXp-xmo", 
        # android_artifact_type: "Apk",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "islamhesham269@gmail.com",
        release_notes: "Second Fastlane Firebase Distribution"
  )
  end
end
